apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tileserver
  template:
    metadata:
      labels:
        app: tileserver
    spec:
      containers:
        - name: tileserver
          image: tileserver:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tileserver-service
spec:
  selector:
    app: tileserver
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
  type: LoadBalancer