server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Rotta per Auth Service
        - id: auth-route
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        
        # Rotta per Ticket Service
        - id: ticket-route
          uri: http://localhost:8082
          predicates:
            - Path=/tickets/**

        # Rotta per Analytics Service
        - id: analytics-route
          uri: http://localhost:8083
          predicates:
            - Path=/analytics/**

        # Rotta per Notification Service
        - id: notification-route
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**